import numpy as np
import random
import matplotlib.pyplot as plt
#sample many random vectors on the unit circle
#apply A to the vectors
#determine the max euclidean norm from results
#resample nearby vectors
#determine max euclidean norm again
#sigma is the max norm
#u1 is where that vector intersects the unit circle
#find v1 at same index in list before applied to A
#v1 is orthogonal to v2
#use v2 to calculate u2 -> Av2/sigma2 = u2

SAMPLE_SIZE=10000
RESAMPLE_SIZE=10000
RESAMPLE_WIDTH=0.5

# determine the vector in list with the highest euclidean norm
# returns its index in the list and norm as a tuple
def max_mag(sample_vectors):
    #initializing storage variables
    max_v = [0, 0]
    max_v_index = -1
    max_v_norm = np.linalg.norm(max_v)

    #determine maximum norm from sample vectors
    for i, v in enumerate(sample_vectors):
        v_norm = np.linalg.norm(v)
        if v_norm > max_v_norm:
            max_v_index = i
            max_v_norm = v_norm

    return max_v_index, max_v_norm

# given the matrix A and its singular vectors/values, generates 2 plots
# plot1: a unit circle with vectors v1 and v2 represented by arrows
# plot2: an ellipse generated by the unit circle applied under A with vectors sigma1u1 and sigma2u2 represented by arrows
def plotSingularValues(A, u, v, sigma):
    #using many evenly spaced values from 0 to 2pi to generate points in a circle
    theta = np.linspace(0, 2*np.pi, 500) 
    circle = np.array([np.cos(theta), np.sin(theta)])
    ellipse = A @ circle #@ operator matrix multiples A with every value in circle

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 8)) #create two seperate plots

    ax1.plot(circle[0], circle[1], label="Unit circle")
    ax2.plot(ellipse[0], ellipse[1], label="A(unit circle)")

    #add arrows for v1 and v2
    ax1.quiver(0, 0, v[0][0], v[0][1], angles="xy", scale_units="xy", scale=1, label="v₁", width=0.005, color="red")
    ax1.quiver(0, 0, v[1][0], v[1][1], angles="xy", scale_units="xy", scale=1, label="v₂", width=0.005, color="green")

    #add label text to a point slightly offset from the end of each arrow
    ax1.text(
        v[0][0]+0.1,
        v[0][1]+0.1,
        "v₁",
        fontsize=12
    )
    ax1.text(
        v[1][0]+0.1,
        v[1][1]+0.1,
        "v₂",
        fontsize=12
    )

    #add arrows for sigma1u1 and sigma2u2
    ax2.quiver(0, 0, u[0][0]*sigma[0], u[0][1]*sigma[0], angles="xy", scale_units="xy", scale=1, label="σ₁u₁", width=0.005, color="red")
    ax2.quiver(0, 0, u[1][0]*sigma[1], u[1][1]*sigma[1], angles="xy", scale_units="xy", scale=1, label="σ₂u₂", width=0.005, color="green")

    #add label text to a point slightly offset from the end of each arrow
    ax2.text(
        sigma[0]*u[0][0]+0.1,
        sigma[0]*u[0][1]+0.1,
        "σ₁u₁",
        fontsize=12
    )
    ax2.text(
        sigma[1]*u[1][0]+0.1,
        sigma[1]*u[1][1]+0.1,
        "σ₂u₂",
        fontsize=12
    )

    #add axis lines
    ax1.axhline(0, c="black")
    ax1.axvline(0, c="black")
    ax2.axhline(0, c="black")
    ax2.axvline(0, c="black")

    #ensure axis scales are the same and show legend
    ax1.axis("equal")
    ax1.legend()
    ax2.axis("equal")
    ax2.legend()
    plt.show()

# approximates the singular vectors/values of the given matrix A using random sampling to first determine what vector on the unit circle is stretched the most
# perhaps using an evenly spaced set of angles when sampling would be better than random sampling
# returns a tuple containing the matrices u and v as well as the singular values stored as a list sigma
def SVD(A):
    #initialize storage variables
    sample_unit_vectors = []
    sample_scaled_vectors = []
    thetas = []
    for i in range(SAMPLE_SIZE):
        theta = random.random()*np.pi*2 #generating a random angle from 0-2pi
        thetas.append(theta)
        sample_unit_vectors.append([np.cos(theta), np.sin(theta)]) #generating a vector of euclidean norm 1 from random theta and appending it to sample collection
        sample_scaled_vectors.append(np.matmul(A, sample_unit_vectors[i]))

    max_v_index, _ = max_mag(sample_scaled_vectors) #finding the vector with max euclidean norm of sampled unit vectors after applied under A

    #resampling vectors within a smaller specified width around the initial max norm vector for additional precision
    resample_unit_vectors = []
    resample_scaled_vectors = []
    for i in range(RESAMPLE_SIZE):
        delta = (random.random()-0.5)*RESAMPLE_WIDTH #random bidirectional change in angle within specified width
        theta = thetas[max_v_index]+delta
        resample_unit_vectors.append([np.cos(theta), np.sin(theta)])
        resample_scaled_vectors.append(np.matmul(A, resample_unit_vectors[i]))

    max_v_index, sigma1 = max_mag(resample_scaled_vectors) #again finding vector with max euclidean norm from the list

    #determining u1 and v1 from the index found by max_mag
    u1 = resample_scaled_vectors[max_v_index]/sigma1
    v1 = resample_unit_vectors[max_v_index]

    #v2 must be a vector orthogonal to v1
    #calculating u2 using: Av2/sigma2 = u2
    v2 = [v1[1], v1[0]*-1]
    Av2 = np.matmul(A, v2)
    sigma2 = np.linalg.norm(Av2)
    u2 = Av2/sigma2

    #compose u, v, and sigma from the values determined above
    u = [u1, u2]
    v = [v1, v2]
    sigma = [sigma1, sigma2]

    return (u, v, sigma)

def main():
    test_A = [[1, 2],
              [0, 2]]
    u, v, sigma = SVD(test_A)
    plotSingularValues(test_A, u, v, sigma)

main()